name: main_v2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.1.0
  connectivity_plus: ^5.0.2

flutter_icons:
  image_path: "assets/appIcon512.png"
  android: true
  ios: false
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
  assets: 
    - assets/citiesDB.json
